<?php
require_once "_config.php";
require "header.php";
?>
<div class="row">
	<div class="span12">
		<h2>Terms of Use</h2>
		<hr>
	<div class="row">	
		<div id="aboutPage" class="span12">
			<p><b>PLEASE READ THIS TERMS OF USE AGREEMENT (THE "TERMS OF USE") CAREFULLY BEFORE ACCESSING OR PARTICIPATING IN ANY CHATROOM, NEWSGROUP, BULLETIN BOARD, MAILING LIST, WEBSITE, TRANSACTION OR OTHER ON-LINE FORUM, WORKSHOP, COURSE, OR SERVICE MADE AVAILABLE BY Galaxy Learn, Inc. (â€œGalaxy Learnâ€�) AT ENTRY-POINT URL (http://www.galaxylearn.com) AND ITS RELATED WEBSITES ("SITE" OR "SITES"). BY USING AND PARTICIPATING IN THE SITES, YOU SIGNIFY AND ACKNOWLEDGE THAT YOU HAVE READ THE TERMS OF USE AND AGREE THAT THE TERMS OF USE CONSTITUTES A BINDING LEGAL AGREEMENT BETWEEN YOU AND Galaxy Learn, AND THAT YOU AGREE TO BE BOUND BY AND COMPLY WITH THE TERMS OF USE. IF YOU DO NOT AGREE TO BE BOUND BY THE TERMS OF USE, PLEASE DO NOT ACCESS THE SITES. THE PARTICIPATING INSTITUTIONS ARE THIRD PARTY BENEFICIARIES OF THE AGREEMENT AND MAY ENFORCE THOSE PROVISIONS BELOW THAT RELATE TO THE PARTICIPATING INSTITUTIONS.</b></p><br />
			<p><u>AGE RESTRICTIONS</u><br />Registration on the Sites is restricted to those individuals over 18 years of age, emancipated minors, or those who possess legal parental or guardian consent, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations and warranties herein. By registering or participating in services or functions on the Sites, you hereby represent that you are over 18 years of age, an emancipated minor or in possession of consent by a legal parent or guardian and have the authority to enter into the terms herein. In addition, those who wish to register and participate must meet the minimum requirements laid out in the Terms of Use (this document) and abide by the Honor Code herein. In addition, certain Workshops may have additional eligibility requirements, as specified on the Workshop website. If you do not qualify or do not agree to these terms, you may not use the Site.</p><br />
			<p><u>RIGHT OF MODIFICATION</u><br />
We reserve the right to change or modify the Terms of Use at our sole discretion at any time. Any change or modification to the Terms of Use will be effective immediately upon posting by us. For any material changes to the Terms, we will take reasonable steps to notify you of such changes. In all cases, your continued use of the Sites after publication of such modifications, with or without notification, constitutes binding acceptance of these modified Terms of Use.
    		<p><u>DISCLAIMER</u><br />
Sites may include forums containing the personal opinions and other expressions of the persons who post entries on a wide range of topics. Neither the User Content (as defined below) on these Sites, nor any links to other websites, are screened, moderated, approved, reviewed or endorsed by Coursera or its participating institutions. By posting to or viewing such forums, you agree that Coursera and any of its participating institutions are not responsible or liable for the content of any postings therein. Coursera reserves the right (but not the obligation) to remove any content from such forums in its discretion.</p><br />
    		<p><u>RULES FOR ONLINE CONDUCT</u><br />
You agree to use the Sites in accordance with all applicable laws. Further, you agree that you will not use the Site for organized partisan political activities. You further agree that you will not e-mail or post any of the following content (â€œProhibited Contentâ€�) anywhere on the Site, or on any other Galaxy Learn computing resources:</p><br />
	<ul>
		<li>Content that defames, harasses or threatens others
		<li>Content that discusses illegal activities with the intent to commit such activities, or encourages others to commit such activities
		<li>Content that infringes or misappropriates another's intellectual property rights, including, but not limited to, copyrights, trademarks or trade secrets
		<li>Content that you do not have the right to disclose under contractual confidentiality obligations or fiduciary duties
		<li>Material that contains obscene (i.e., pornographic) language or images
		<li>Advertising, promotional materials, or any form of commercial solicitation
		<li>Content that otherwise harms other users or visitors to the Sites
		<li>Content that is otherwise unlawful or that violates any applicable local, state, national or international law.
	</ul>
	
Although Galaxy Learn does not routinely screen or monitor content posted by users to the Site, Galaxy Learn reserves the right to remove Prohibited Content of which it becomes aware, but is under no obligation to do so.
Copyrighted material, including without limitation software, graphics, text, photographs, sound, video and musical recordings, may not be placed on the Site without the express permission of the owner of the copyright in the material, or other legal entitlement to use the material.
In addition, as a condition of accessing the Sites, you agree not to (a) reproduce, duplicate, copy, sell, resell or exploit any portion of the Sites other than as expressly allowed under these Terms of Use; (b) use Galaxy Learnâ€™s or any Participating Institution's name, trademarks, server or other materials in connection with, or to transmit, any unsolicited communications or emails; Â© use any high-volume, automated or electronic means to access the Sites (including without limitation, robots, spiders, scripts or web-scraping tools); (d) frame the Sites, place pop-up windows over its pages or otherwise affect the display of its page; or (e) interfere with or disrupt the Sites or servers or networks connected to the Sites, or disobey any requirements, procedures, policies or regulations of networks connected to the Sites.
Finally, you agree that you will not access or attempt to access any other user's account, or misrepresent or attempt to misrepresent your identity while using the Sites.

						<p><u>USER ACCOUNTS</u><br />
In order to fully participate in all Site activities, you must register for a personal account on the Site (a â€œUser Accountâ€�) by providing an email address and a password for your User Account. You agree that you will never divulge or share access or access information to your User Account with any third party for any reason. You also agree to that you will create, use, and access only one User Account, and that you will not access the Site using multiple User Accounts.
In setting up your User Account, you may be prompted or required to enter additional information, including but not limited to your name and location. Additional information may be required to confirm your identity. You represent that all information provided by you is accurate, current and complete and you agree that you will maintain and update your information to keep it accurate, current and complete. You acknowledge that if any information provided by you is untrue, inaccurate, not current or incomplete, we reserve the right to terminate your use of the Sites.</p><br />

						<p><u>PRIVACY POLICY</u><br />
You understand that any personal information you submit to Galaxy Learn on the Sites will be treated by Galaxy Learn in the manner described in the Privacy Policy.</p><br />

						<p><u>ONLINE COURSE AND CERTIFICATIONS</u><br />
The Sites will, from time to time, offer online workshops in a specific area of study or on a particular topic (an â€œOnline Workshopâ€�). Galaxy learn and the instructors of the Online Workshops reserve the right to cancel, interrupt or reschedule any Online Workshop or modify its content as well as the point value or weight of any assignment, exam or other evaluation of progress. Online Workshops offered are subject to the Disclaimer of Warranties / Limitation of Liabilities section below.
For some courses, subject to your satisfactory performance in the Online Workshop as determined in the sole discretion of the instructors and the Participating Institutions, you may be awarded a statement acknowledging your completion of the class (â€œStatement of Accomplishment"). This Statement of Accomplishment, if provided to you, would be from Galaxy Learn and/or from the instructors. You acknowledge that the Statement of Accomplishment, if provided to you, may not be affiliated with Galaxy Learn or any college or university. Further, Galaxy Learn offers the right to offer or not offer any such Statement of Accomplishment for a class. You acknowledge that the Statement of Accomplishment, and Galaxy Learnâ€™s Online Workshops, will not stand in the place of a course taken at an accredited institution, and do not convey academic credit. You acknowledge that neither the instructors of any Online Workshops nor the associated Participating Institutions will be involved in any attempts to get the workshop recognized by any educational or accredited institution. The format of the Statement of Accomplishment will be determined at the discretion of Galaxy Learn and the instructors, and may vary by class in terms of formatting, e.g., whether or not it reports your detailed scores or grades in the class, and in other ways.
You may not take any Online Workshop offered by Galaxy Learn or use any Statement of Accomplishment as part of any tuition-based or for-credit certification or program for any college, university, or other academic institution without the express written permission from Galaxy Learn. Such use of an Online Course or Statement of Accomplishment is a violation of these Terms of Use.</p><br />

						<p><u>DISCLAIMER OF STUDENT-UNIVERSITY RELATIONSHIP</u><br />
You agree and acknowledge that nothing in these Terms of Use or otherwise with respect to your access or use of any Online Course or Site (a) establishes any relationship between you and any university or other educational institution with which Galaxy Learn may be affiliated, (b) enrolls or registers you in any university or other educational institution, or in any course offered by any university or other educational institution, or Â© entitles you to access or use the resources of any university or other educational institution beyond the Online Workshops provided by the Sites.</p><br />

						<p><u>PERMISSION TO USE MATERIALS</u><br />
All content or other materials available on the Sites, including but not limited to code, images, text, layouts, arrangements, displays, illustrations, audio and video clips, HTML files and other content are the property of Galaxy Learn and/or its affiliates or licensors and are protected by copyright, patent and/or other proprietary intellectual property rights under the United States and foreign laws. In consideration for your agreement to the terms and conditions contained here, Galaxy Learn grants you a personal, non-exclusive, non-transferable license to access and use the Sites. You may download material from the Sites only for your own personal, non-commercial use. You may not otherwise copy, reproduce, retransmit, distribute, publish, commercially exploit or otherwise transfer any material, nor may you modify or create derivatives works of the material. The burden of determining that your use of any information, software or any other content on the Site is permissible rests with you.</p><br />

						<p><u>USER MATERIAL SUBMISSION</u><br />
The Sites may provide you with the ability to upload certain information, text, or materials, including without limitation, any information, text or materials you post on the Sitesâ€™ public forums such as the wiki or the discussion forums (â€œUser Contentâ€�). With respect to User Content you submit or otherwise make available in connection with your use of the Site, and subject to the Privacy Policy, you grant Galaxy Learn and the Participating Institutions a fully transferable, worldwide, perpetual, royalty-free and non-exclusive license to use, distribute, sublicense, reproduce, modify, adapt, publicly perform and publicly display such User Content. To the extent that you provide User Content, you represent and warrant to Galaxy Learn and the Participating Institutions that (a) you have all necessary rights, licenses and/or clearances to provide and use User Content and permit Galaxy Learn and the Participating Institutions to use such User Content as provided above; (b) such User Content is accurate and reasonably complete; Â© as between you and Galaxy Learn you shall be responsible for the payment of any third party fees related to the provision and use of such User Content and (d) such User Content does not and will not infringe or misappropriate any third party rights (including without limitation privacy, publicity, intellectual property and any other proprietary rights, such as copyright, trademark and patent rights) or constitute a fraudulent statement or misrepresentation or unfair business practice.
The Sites may also provide you with ability to upload or send information to Galaxy Learn regarding the Sites or related services (â€œFeedbackâ€�). By submitting the Feedback, you hereby grant Galaxy Learn and the Participating Institutions an irrevocable license to use, disclose, reproduce, distribute, sublicense, prepare derivative works of, publicly perform and publicly display any such submission.</p><br />

						<p><u>LINKS TO OTHER SITES</u><br />
The Sites may include hyperlinks to sites maintained or controlled by others. Neither Galaxy Learn nor the Participating Institutions are responsible for nor do they routinely screen, approve, review or endorse the contents of or use of any of the products or services that may be offered at these sites.</p><br />

						<p><u>ONLINE EDUCATION RESEARCH</u><br />
Records of your participation in Online Workshops may be used for researching online education. In the interests of this research, you may be exposed to slight variations in the course materials that will not substantially alter your learning experience. All research findings will be reported at the aggregate level and will not expose your personal identity.</p><br />

						<p><u>FEES AND TAXES</u><br />
In selected Online Workshops, you may have the option to enroll for additional services (e.g., the Signature Track or ACE-CREDIT courses) in specific courses for a fee. Unless otherwise stated, all fees are quoted in U.S. Dollars. You are responsible for paying all fees and applicable taxes associated in a timely manner with a payment accepted by the Site. If your payment method fails or your account is past due, we may collect fees using other collection mechanisms. Galaxy Learn reserves the right to change the fees at any time in its sole discretion. Any change, update, or modification will be effective immediately upon posting on our Site.</p><br />

						<p><u>REFUND POLICY</u><br />
If you elect to cancel your participation in the Signature Track of a course, Galaxy Learn will offer you a complete refund up until two weeks after the date when Signature Track registration period closes for the course. After that, if you are unable to complete the course, you will be given a course coupon valid for one year from the end date of the course. This coupon will only be valid for a future offering of the exact same course. However, please be aware that Galaxy Learn cannot provide guarantees for class repeat schedules.
If you are found to be in violation of Galaxy Learnâ€™s Honor Code and academic integrity policies or Terms of Service, you will not be issued a refund or coupon.
To request a refund, please contact us.</p><br />

						<p><u>NOTICE FOR CALIFORNIA USERS</u><br />
Under California Civil Code Section 1789.3, California Website users are entitled to the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 1625 N. Market Blvd., Suite S-202, Sacramento, California 95834, or by telephone at (800) 952-5210.</p><br />

						<p><u>CHOICE OF LAW/FORUM SELECTION</u><br />
Sites are managed by Galaxy Learn, located in Santa Clara County, California. You agree that any dispute arising out of or relating to these Terms of Use or any content posted to a Site, including copies and republication thereof, whether based in contract, tort, statutory or other law, will be governed by the laws of the State of California, excluding its conflicts of law provisions. You further consent to the personal jurisdiction of and exclusive venue in the federal and state courts located in and serving Santa Clara County, California as the legal forum for any such dispute.</p>
Excluding claims for injunctive or other equitable relief, for claims related to the Galaxy Learn Sites where the total amount sought is less than ten thousand U.S. Dollars ($10,000.00 USD), either Galaxy Learn or You may elect at any point during the dispute to resolve the claim through binding, non-appearance-based arbitration. The dispute will then be resolved using an established alternative dispute resolution ("ADR") provider, mutually agreed upon by You and Galaxy Learn. The parties and the selected ADR provider shall not involve any personal appearance by the parties or witnesses, unless otherwise mutually agreed by the parties; rather, the arbitration shall be conducted, at the option of the party seeking relief, online, by telephone, online, or via written submissions alone. Any judgment rendered by the arbitrator may be entered in any court of competent jurisdiction.</p><br />

						<p><u>DISCLAIMER OF WARRANTY / LIMITATION OF LIABILITIES</u><br />
THE SITES AND ANY INFORMATION, PRODUCTS OR SERVICES THEREIN ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. Galaxy Learn AND ITS PARTICIPATING INSTITUTIONS, THEIR INSTRUCTORS AND THEIR STAFF (THE â€œGalaxy Learn PARTIESâ€�) DO NOT WARRANT, AND HEREBY DISCLAIM ANY WARRANTIES, EITHER EXPRESS OR IMPLIED, WITH RESPECT TO THE ACCURACY, ADEQUACY OR COMPLETENESS OF ANY ONLINE COURSE, SITE, INFORMATION OBTAINED FROM A SITE, OR LINK TO A SITE. THE Galaxy Learn PARTIES DO NOT WARRANT THAT SITES WILL OPERATE IN AN UNINTERRUPTED OR ERROR-FREE MANNER OR THAT SITES ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WITHOUT LIMITING THE FOREGOING, THE Galaxy Learn PARTIES DO NOT WARRANT THAT (A) THE ONLINE COURSES OR SITES WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS OR ACHIEVE THE INTENDED PURPOSES, (B) THE ONLINE COURSES OR SITES WILL NOT EXPERIENCE OUTAGES OR OTHERWISE BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE, Â© THE INFORMATION OR SERVICES OBTAINED THROUGH OR FROM THE ONLINE COURSES OR SITES WILL BE ACCURATE, COMPLETE, CURRENT, ERROR-FREE, COMPLETELY SECURE OR RELIABLE, OR (D) THAT DEFECTS IN OR ON THE ONLINE COURSES OR SITES WILL BE CORRECTED. NONE OF THE Galaxy Learn PARTIES MAKE ANY REPRESENTATION REGARDING YOUR ABILITY TO TRANSMIT AND RECEIVE INFORMATION FROM OR THROUGH THE SITES, AND YOU AGREE AND ACKNOWLEDGE THAT YOUR ABILITY TO ACCESS THE ONLINE COURSES AND SITES MAY BE IMPAIRED. THE Galaxy Learn PARTIES DISCLAIM ANY AND ALL LIABILITY RESULTING FROM OR RELATED TO SUCH EVENTS OR THE ACCESS OR USE OF THE ONLINE COURSES OR SITES OR ANY INFORMATION OR SERVICES RELATED TO THEM.
YOU ACKNOWLEDGE AND AGREE THAT ANY ACCESS TO OR USE OF THE ONLINE COURSES AND SITES OR SUCH INFORMATION OR SERVICES IS AT YOUR OWN RISK.
EXCEPT AS PROHIBITED BY LAW, YOU AGREE THAT THE Galaxy Learn PARTIES WILL NOT BE LIABLE TO YOU FOR ANY LOSS OR DAMAGES ARISING OUT OF OR RELATING TO THESE TERMS OF USE OR YOUR (OR ANY THIRD PARTY'S) USE OR INABILITY TO USE AN ONLINE COURSE, SITE, DATA LOSS, YOUR PLACEMENT OF CONTENT ON A SITE, YOUR RELIANCE UPON INFORMATION OBTAINED FROM OR THROUGH AN ONLINE COURSE OR SITE, OR ANY OTHER POTENTIAL CLAIMS RELATED TO THE ONLINE COURSES OR SITES.
EXCEPT AS PROHIBITED BY LAW, THE Galaxy Learn PARTIES WILL NOT HAVE LIABILITY FOR ANY CONSEQUENTIAL, INDIRECT, PUNITIVE, SPECIAL OR INCIDENTAL DAMAGES, WHETHER FORESEEABLE OR UNFORESEEABLE, (INCLUDING, BUT NOT LIMITED TO, CLAIMS FOR DEFAMATION, ERRORS, LOSS OF DATA, OR INTERRUPTION IN AVAILABILITY OF DATA), ARISING OUT OF OR RELATING TO THESE TERMS OF USE, YOUR USE OR INABILITY TO USE ANY ONLINE COURSE OR SITE, DATA LOSS, ANY PURCHASES ON THIS SITE, YOUR PLACEMENT OF CONTENT ON A SITE, OR YOUR RELIANCE UPON INFORMATION OBTAINED FROM OR THROUGH ANY ONLINE COURSE OR SITE, WHETHER BASED IN CONTRACT, TORT, STATUTORY OR OTHER LAW, EXCEPT ONLY IN THE CASE OF DEATH OR PERSONAL INJURY WHERE AND ONLY TO THE EXTENT THAT APPLICABLE LAW REQUIRES SUCH LIABILITY. Galaxy Learnâ€™s TOTAL CUMULATIVE LIABILITY ARISING OUT OF OR RELATED TO THE USER'S USE OF THE Galaxy Learn SITES WILL NOT EXCEED TWENTY U.S. DOLLARS ($20) OR THE TOTAL AMOUNT OF FEES RECEIVED BY Galaxy Learn FROM THE USER FOR THE USE OF THE Galaxy Learn SITES DURING THE PAST 12 MONTHS OF USE, WHICHEVER IS GREATER.
YOU ACKNOWLEDGE AND AGREE THAT THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH IN THIS TERMS OF SERVICE REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN YOU AND THE Galaxy Learn PARTIES, AND THAT THESE LIMITATIONS ARE AN ESSENTIAL BASIS TO Galaxy Learnâ€™s ABILITY TO MAKE THE Galaxy Learn SITES AVAILABLE TO YOU ON AN ECONOMICALLY FEASIBLE BASIS.
YOU AGREE THAT ANY CAUSE OF ACTION RELATED TO THE Galaxy Learn SITES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</p><br />

						<p><u>COPYRIGHT POLICY</u><br />
The Digital Millennium Copyright Act (the â€œDMCAâ€�) provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law.
If you believe in good faith that materials on the Galaxy Learn Sites infringe your copyright, you (or your agent) may send us a notice requesting that the material be removed, or access to it blocked.
The notice must include the following information: (a) a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; (b) identification of the copyrighted work claimed to have been infringed (or if multiple copyrighted works located on the Site are covered by a single notification, a representative list of such works); Â© identification of the material that is claimed to be infringing or the subject of infringing activity, and information reasonably sufficient to allow Galaxy Learn to locate the material on the Site; (d) the name, address, telephone number, and email address (if available) of the complaining party; (e) a statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (f) a statement that the information in the notification is accurate and, under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
Notices must meet the then-current statutory requirements imposed by the DMCA; see http://www.loc.gov/copyright for details. Notices and counter-notices with respect to the Site should be sent to:
Copyright Agent
Galaxy Learn
950 San Pierre Way
Mountain View, CA 94040
(650) 336-7454
We suggest that you consult your legal advisor before filing a notice. Also, be aware that there can be penalties for false claims under the DMCA.</p><br />

						<p><u>INDEMNIFICATION</u><br />
You agree to indemnify, defend and hold harmless Galaxy Learn and the Participating Institutions, their respective subsidiaries and affiliates, and each of their respective officers, directors, agents, employees, and assignees, including the instructors of the Participating Institutions, from any and all claims, liabilities, expenses and damages, including reasonable attorneysâ€™ fees and costs, made by any third party relating to or arising out of (a) your use or attempted use of the Sites or Online Course in violation of the Terms of Use; (b) your violation of any law or rights of any third party, or Â© information that you post or otherwise make available on the Sites or through the Online Course, including without limitation any claim of infringement or misappropriation of intellectual property or other proprietary rights.</p><br />

						<p><u>TERMINATION RIGHTS</u><br />
You agree that each of Galaxy Learn and the Participating Institutions, in their sole discretion, may terminate your use of the Site or your participation in it thereof, for any reason or no reason and that none of the Galaxy Learn Parties shall have any liability to you for any such action. You further acknowledge that for the purpose of any Galaxy Learn course your sole relationship with Galaxy Learn and the Participating Institution is as defined in these Terms of Use; for the avoidance of doubt, you do not have student status at any Participating Institution through a Galaxy Learn workshop and you are not entitled to any grievance or other resolution process for student disputes at any Participating Institution. You further agree that Galaxy Learn has the right to cancel, delay, reschedule or alter the format of any Online Course or Workshop at any time, and that none of the Galaxy Learn Parties shall have any liability to you for any such action. If you no longer desire to participate in the Site, you may terminate your participation therein upon notice to Galaxy Learn.
Effective as of 12 April, 2013.
Privacy Policy</p><br />

						<p><u>WHAT INFORMATION THIS PRIVACY POLICY COVERS</u><br />
Some of our Site's functionality can be used without revealing any personal information, though for features or services related to the Online Workshop, personal information is required. If you do not use these specific features or services on the Site, then the only information we collect will be "Non-Personal Information" (i.e., information that cannot be used to identify you). Non-Personal Information includes information such as the web pages that you have viewed. In order to access certain features and benefits on our Site, you may need to submit "Personally Identifiable Information" (i.e., information that can be used to identify you). Personally Identifiable Information can include information such as your name and email address, among other things. You are responsible for ensuring the accuracy of the Personally Identifiable Information you submit to Galaxy Learn. Inaccurate information may affect your ability to use the Site, the information you receive when using the Site, and our ability to contact you. For example, your email address should be kept current because that is one of the primary manners in which we communicate with you.</p><br />

						<p><u>WHAT YOU CONSENT TO BY USING OUR SITE</u><br />
Please understand that by submitting any Personally Identifiable Information to us, you consent and agree that we may collect, use and disclose such Personally Identifiable Information in accordance with this Privacy Policy and our Terms of Use, and as permitted or required by law. If you do not agree with these terms, then please do not provide any Personally Identifiable Information to us. If you refuse or withdraw your consent, or if you choose not to provide us with any required Personally Identifiable Information, we may not be able to provide you with the services that can be offered on our Site.</p><br />

						<p><u>WHAT INFORMATION WE COLLECT</u><br />
We gather two types of information about users through the Site:
Non-Personal Information. When users come to our Site, we may track, collect and aggregate Non-Personal Information indicating, among other things, which pages of our Site were visited, the order in which they were visited, when they were visited, and which hyperlinks were "clicked." We also collect information from the URLs from which you linked to our Site. Collecting such information may involve logging the IP address, operating system and browser software used by each user of the Site. Although such information is not Personally Identifiable Information, we may be able to determine from an IP address a user's Internet Service Provider and the geographic location of his or her point of connectivity.
We also use or may use cookies and/or web beacons to help us determine and identify repeat visitors, the type of content and sites to which a user of our Site links, the length of time each user spends at any particular area of our Site, and the specific functionalities that users choose to use. Essentially, cookies are a user's identification card for the Galaxy Learn servers. Web beacons are small graphic files linked to our servers that allow us to track your use of our Site and related functionalities. Cookies and web beacons allow Galaxy Learn to serve you better and more efficiently, and to personalize your experience at our Site. Cookies and web beacons are not used to retain Personally Identifiable Information. From time to time we may also use additional typical methods of collecting data.
You should be able to control how and whether cookies will be accepted by your web browser. Most browsers offer instructions on how to reset the browser to reject cookies in the "Help" section of the toolbar. If you reject our cookies, many functions and conveniences of this Site may not work properly.
Personally Identifiable Information. We collect Personally Identifiable Information that you provide to us when you sign-up for email updates or Online Courses or Workshops, participate in our public forums, send us email messages, and/or participate in Online Courses or other services on our Site. Among other things, we may use the Personally Identifiable Information that you provide to respond to your questions, provide you the specific course and/or services you select, send you updates about Online Courses or Workshops offered by Galaxy Learn or other Galaxy Learn events, and send you email messages about Site maintenance or updates, among other things.
Updates. Galaxy Learn may offer you the ability to receive updates either via email or by posting on portions of the Site only accessible to registered users. In order to subscribe to these services, you may be required to provide us with Personally Identifiable Information such as your name and email address.
Forums. Galaxy Learn may offer public forums from time to time (the "Forums") where you can share comments and thoughts. In order to participate in the Forums, you may be required to register with us and/or provide us with Personally Identifiable Information such as your name and email address. Personally Identifiable Information shall not include any information posted or sent by or to you via any public Forum.
Participation in Online Courses and Workshops. From time to time, Galaxy Learn may offer you the opportunity to participate in an Online Course and Workshops on or through the Site. If you desire to participate in a course or workshop, you will be asked to provide us with certain information necessary to conduct such a course. This information may include, among other things, your name and email address.
Identity Verification. Galaxy Learn may offer you the ability to verify your identity (e.g., through the Signature Track or ACE-CREDIT courses) for selected classes. In order to enroll for these services, you may be required to provide us with Personally Identifiable Information such as your name, address, a headshot taken using a webcam, a photo identification document, and a sample of your typing patterns.
Communications with Galaxy Learn. We may receive Personally Identifiable Information when you send us an email message or otherwise contact us. Third Party Sites. We may receive Personally Identifiable Information when you access or log-in to a third party site, e.g., Facebook, from our Sites. This may include the text and/or images of your Personally Identifiable Information available from the third party site.</p><br />

						<p><u>HOW WE USE THE INFORMATION</u><br />
Please take some time to familiarize yourself with the different ways Galaxy Learn uses the information that we gather.
Non-Personal Information. We use Non-Personal Information in aggregate form to build higher quality, more useful services by performing statistical analyses of the collective characteristics and behavior of our users, and by measuring demographics and interests regarding specific areas of our Site. We may also use it for other business purposes.
Personally Identifiable Information. Except as set forth in this Privacy Policy or as specifically agreed to by you, Galaxy Learn will not disclose any Personally Identifiable Information we gather from you on the Site. In addition to the other uses set forth in this Privacy Policy, we may disclose and otherwise use Personally Identifiable Information as described below.
Updates. We use Personally Identifiable Information collected when you sign-up for our various email or update services to send you the messages in connection with the Site or an Online Course. We may also archive this information and/or use it for future communications with you.
Forums. To facilitate your use of the Forums, we use Personally Identifiable Information collected during your use of the Forums. In addition, we may publish this information via extensions of our Platform that use third-party services, like mobile applications. We also reserve the right to reuse Forum posts containing Personally Identifiable Information in future iterations of this course or others, for the purpose of enhancing future course offerings. We may archive this information and/or use it for future communications with you and/or your designee(s), and/or provide it to the University or the instructor(s) associated with the Course. We may also use or publish posts submitted on the forums without using Personally Identification Information.
Participation in Online Courses and Workshops. We use the Personally Identifiable Information that we collect from you when you participate in an Online Course or Workshop through the Site for processing purposes, including but not limited to tracking attendance, progress and completion of an Online Course or Workshop. We may also share your Personally Identifiable Information and your performance in a given Online Course with the instructor or instructors who taught the course, with teaching assistants or other individuals designated by the instructor or instructors to assist with the creation, modification or operation of the course, and with the university or universities with which they are affiliated. Also, we may archive this information and/or use it for future communications with you.
Identity Verification. For services that require identity verification (e.g., the Signature Track or ACE-CREDIT courses), we use the Personally Identifiable Information that we collect for verifying your identity, and for authenticating that submissions made on the Site were made by you. Your photo identification document will be deleted after successful verification of your profile information.
Communications with Galaxy Learn. When you send us an email message or otherwise contact us, we may use the information provided by you to respond to your communication and/or as described in this Privacy Policy. We may also archive this information and/or use it for future communications with you.
Communications with Galaxy Learn Business Partners. We may share your Personally Identifiable Information with business partners of Galaxy Learn to receive communications from such parties that you have opted in to.
Disclosure to Coursera Operations and Maintenance Contractors. Our operations and maintenance contractors may have limited access to your Personally Identifiable Information in the course of providing products or services to us. These contractors may include vendors and suppliers that provide us with technology, services, and/or content related to the operation and maintenance of the Site or the Online Course. Access to your Personally Identifiable Information by these contractors is limited to the information reasonably necessary for the contractor to perform its limited function for us.
Government Authorities, Legal Rights and Actions. Galaxy Learn may share your Personally Identifiable Information with various government authorities in response to subpoenas, court orders, or other legal process; to establish or exercise our legal rights or to protect our property; to defend against legal claims; or as otherwise required by law. In such cases we reserve the right to raise or waive any legal objection or right available to us. We also may share your Personally Identifiable Information when we believe it is appropriate to investigate, prevent, or take action regarding illegal or suspected illegal activities; to protect and defend the rights, property, or safety of Galaxy Learn, the Site, our users, customers, or others; and in connection with our Terms of Use and other agreements.
Disclosure to Acquirers. Galaxy Learn may disclose and/or transfer your Personally Identifiable Information to an acquirer, assignee or other successor entity in connection with a sale, merger, or reorganization of all or substantially all of the equity, business or assets of Galaxy Learn to which your Personally Identifiable Information relates.</p><br />

<p><u>EXTERNAL LINKS</u><br />
For your convenience we may provide links to sites operated by organizations other than Galaxy Learn ("Third Party Sites") that we believe may be of interest to you. We do not disclose your Personally Identifiable Information to these Third Party Sites without obtaining your consent. We do not endorse and are not responsible for the privacy practices of these Third Party Sites. If you choose to click on a link to one of these Third Party Sites, you should review the privacy policy posted on the other site to understand how that Third Party Site collects and uses your Personally Identifiable Information.</p><br />

<p><u>CONFIDENTIALITY & SECURITY OF PERSONALLY IDENTIFIABLE INFORMATION</u><br />
We consider the confidentiality and security of your information to be of the utmost importance. We will use commercially reasonable efforts to keep your Personally Identifiable Information private and will not share it with third parties, except as otherwise provided in this Privacy Policy, or unless we have good faith belief that such disclosure is necessary in special cases, such as a physical threat to you or others. Galaxy Learn takes reasonable measures to protect your Personally Identifiable Information from disclosure to or access by third parties. Please note that we do not guarantee the security of Personally Identifiable Information, and there is some risk that an unauthorized third party may find a way to circumvent our security systems or that transmission of your information over the Internet will be intercepted.</p><br />

<p><u>UPDATING OR DELETING YOUR PERSONALLY IDENTIFIABLE INFORMATION</u><br />
We maintain a procedure in order to help you confirm that your Personally Identifiable Information remains correct and up-to-date or choose whether or not you wish to receive material from us or some of our partners.
You may also update your Personally Identifiable Information by logging into the Site and visiting your user account page. Keep in mind, however, that there will be residual information that will remain within our databases, access logs and other records, which may or may not contain your Personally Identifiable Information.</p><br />

<p><u>CHANGING OUR PRIVACY POLICY</u><br />
Please note that we review our privacy practices from time to time, and that these practices are subject to change. Any change, update, or modification will be effective immediately upon posting on our Site. We will notify you of any material change to this Privacy Policy by posting a notice on our Site's homepage for a reasonable period of time following such update, and by changing the effective date (located at the bottom of this page). Be sure to return to this page periodically to ensure familiarity with the most current version of this Privacy Policy.</p><br />

<p><u>PROTECTING CHILDREN'S PRIVACY</u><br />
Galaxy Learn strongly believes in protecting the privacy of children. In line with this belief, we do not knowingly collect or maintain Personally Identifiable Information on our Site from persons under 13 years of age. We will take appropriate steps to delete any Personally Identifiable Information of persons less than 13 years of age that has been collected on our Site without verified parental consent upon learning of the existence of such Personally Identifiable Information.
Effective as of 12 April, 2013.</p><br />
Honor Code
All users participating must agree to abide by the following code of conduct:
1.	I will register for only one account.
2.	My answers to homework, quizzes and exams will be my own work (except for assignments that explicitly permit collaboration).
3.	I will not make solutions to homework, quizzes or exams available to anyone else. This includes both solutions written by me, as well as any official solutions provided by the course staff.
4.	I will not engage in any other activities that will dishonestly improve my results or dishonestly improve/hurt the results of others.
Effective as of 12 April, 2013 </p>
		</div>
	</div>
	<div id="contactButton" >
		<p><b>Teachers, schools, other institutional users:</b> Please contact Galaxy Learn for special pricing and custom-configured systems and analytics.</p>
		<a href="mailto:<?php echo CONTACT_EMAIL; ?>" class="btn btn-large btn-primary">Contact Us</a>
	</div>
	</div>
</div>
<?php
require "footer.php";
